image: Visual Studio 2017

environment:
  nodejs_version: ""

platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version
  - npm install --no-save nan tree-sitter-cli readdir-enhanced
  - npm run build
  - npm install

test_script:
  - npm test

build: off

branches:
  only:
    - master
